#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build"

# Prepare $newpath for string replacement (empty if $path is root or $path if subdir is defined)
newpath=""
if [[ $path != '/' ]]; then newpath=$path; fi

# Replace path placeholder recursively in all files of the app folder
grep -rli '__YNH_DOMAIN____YNH_SUBDIR_PATH__' $install_dir/* | xargs sed -i "s@/__YNH_DOMAIN____YNH_SUBDIR_PATH__@$domain$newpath@g"
grep -rli '/__YNH_SUBDIR_PATH__' $install_dir/* | xargs sed -i "s@/__YNH_SUBDIR_PATH__@$newpath@g"

# Keep only the core app and remove useless files and folders related with upstream website
remove=("404.html" "CNAME" "converter" "docs.html" "index.html" "legal" "robots.txt" "sitemap-0.xml" "sitemap.xml" "tools" "type")
for item in "${remove[@]}"; do
    if [ -e "$install_dir/$item" ]; then
        rm -rf "$install_dir/$item"
    fi
done

# Install CDN package locally
ynh_setup_source --dest_dir="$install_dir/libs/monaco-editor/0.34.0/" --source_id="monaco-editor"
grep -rli 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.34.0/' $install_dir/_next/static/chunks/* | xargs sed -i "s@cdnjs.cloudflare.com/ajax@$domain$path@g"

# Apply permissions
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
