name: ynh-build-on-demand

on:
  workflow_dispatch

jobs: 
  ynh-app-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build release
        id: build_release
        run: | 
          chmod +x scripts/build
          ./scripts/build
          
      - name: Prepare draft release
        id: draft_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.build_release.outputs.YNH_RELEASE_FILE }}
          fail_on_unmatched_files: true
          tag_name: ${{ steps.build_release.outputs.YNH_RELEASE_VERSION }}
          draft: true
          prerelease: false
          make_latest: true
          body: |
            Version built for Yunohost using `scripts/build` and `.github/workflows/ynh-build-on-demand.yml` in order to split upstream website from the app and ensure sub-directory install compatibility.
            ### Changelog
            Cf. upstream release note: ${{ steps.diff_url.outputs.COMPARE_URL }}

      - name: Replace URL & SHA256 in manifest.toml
        run: |
          sed -i '/\[resources.sources.ynh_build\]/,/sha256/ {
              /url/s|=.*$|= "${{ steps.build_release.outputs.YNH_RELEASE_URL }}"|
              /sha256/s|=.*$|= "${{ steps.build_release.outputs.YNH_RELEASE_SHA }}"|
          }' manifest.toml

      - name: Create pull request
        run: |
          CURRENT_BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          PR_URL="$(gh pr list --head "${CURRENT_BRANCH_NAME}" --state open --json url --jq .[].url)"
          if [[ -n "${PR_URL}" ]]; then
            echo "PR already exists for the current branch -> ${PR_URL}"
            exit 0
          else
            gh pr create --base master --head testing --title 'Update to ${{ steps.build_release.outputs.YNH_RELEASE_VERSION }}' --body '
            Upstream upgrade is now built for YNH and ready to be released in the current repository: ${{ steps.draft_release.outputs.url }}
            - [ ] Make sure the release is published before testing this PR.
            - [ ] Rename PR title with appropriate version number.
           '
          fi 
